CREATE TABLE VUTA_TRG_BAN_HANG (
    COUNTRY VARCHAR2(50 BYTE),
    PRODUCT VARCHAR2(50 BYTE),
    DISCOUNT_BAND VARCHAR2(50 BYTE),
    COGS NUMBER,
    UNITS_SOLD NUMBER,
    SALE_PRICE NUMBER,
    DISCOUNTS NUMBER,
    GROSS_SALES NUMBER,
    SALES NUMBER,
    PROFIT NUMBER,
    SALE_DATE DATE
);
CREATE TABLE VUTA_TRG_BAO_CAO_THANG (
    MONTH VARCHAR2(6),
    Discounts NUMBER,
    Gross_Sales NUMBER,
    Sales NUMBER,
    Profit NUMBER
);
CREATE TABLE TRG_SAN_PHAM (
    YEAR VARCHAR2(4),
    Product VARCHAR2(50 BYTE),
    Sales NUMBER,
    Profit NUMBER
);
ALTER TABLE TRG_SAN_PHAM
RENAME TO VUTA_TRG_SAN_PHAM;

CREATE TABLE ETL_LOG (
    ETL_DATE DATE NOT NULL,
    JOB_NAME VARCHAR2(255) NOT NULL,
    BUSINESS_DATE DATE,
    FLAG CHAR(1) CHECK (FLAG IN ('Y', 'N')),
    SUCCESS VARCHAR2(1) CHECK (SUCCESS IN ('Y', 'N', NULL))
);
ALTER TABLE ETL_LOG
RENAME TO VUTA_ETL_LOG;
COMMIT;

SELECT MAX(FLAG)
FROM ODI_SALES_DEV.DOTT_ETL_LOGS
WHERE ETL_DATE =TRUNC(SYSDATE)
  AND JOB_NAME = ''



SELECT * FROM VUTA_TRG_BAN_HANG;
SELECT DISTINCT TO_CHAR(SALE_DATE, 'YYYYMM') FROM DOTT_TRG_BAN_HANG;
SELECT DISTINCT TO_CHAR(SALE_DATE, 'YYYYMM') FROM VUTA_TRG_BAN_HANG;